server.port=8443
server.servlet.context-path=/finance
server.ssl.enabled=true
server.ssl.key-store=classpath:ssl.pkcs12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=pkcs12
server.ssl.key-alias=localhost

spring.application.name=finance
spring.cache.jcache.config=classpath:ehcache.xml
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/finance
spring.datasource.username=finance
spring.datasource.password=finance

spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=jcache
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.jpa.hibernate.SpringSessionContext
spring.jpa.properties.hibernate.default_schema=finance
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.javax.cache.missing_cache_strategy=create
spring.jpa.properties.hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
spring.jpa.properties.hibernate.show_sql=true

